### ISSUE TITLE
Ported specialsnowflek auto PR generation from /TG/

### ISSUE THREAD

**Issue by oisin100** [yogstation13/yogstation-classic#962]
Basically, you can write your changelogs in your PR's instead of pushing a new .yml file.

Usage

:cl: John Doe
rscadd: New changelog generation system ported from /TG/!
/:cl:

This would be equivalent to writting a yml file and putting the following in.

```
author: John Doe
 delete-after: True
 changes: 
   - rscadd: "New changelog generation system ported from /TG/!"
```

This should be working right now. Try not to break it!

EDIT: Ignore this edit.
